package br.com.faceZuck.model.enums;

public enum EducationLevel {

	INCOMPLETE_ELEMENTARY,
	COMPLETE_ELEMENTARY,
	INCOMPLETE_HIGH_SCHOOL,
	COMPLETE_HIGH_SCHOOL,
	INCOMPLETE_UNIVERSITY,
	COMPLETE_UNIVERSITY,
	MASTERS,
	DOCTORATE,
	POSTDOCTORATE;

}
